In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../data.csv')

In [3]:
df.columns

Index(['element_type', 'subreddit_id', 'subreddit_display_name',
       'subreddit_subscribers', 'post_id', 'title', 'author', 'created_utc',
       'selftext', 'score', 'num_comments', 'url', 'gilded', 'num_crossposts',
       'over_18', 'permalink', 'upvote_ratio', 'comment_id', 'parent_id',
       'link_id', 'author_fullname', 'author_premium', 'num_reports', 'body',
       'edited', 'depth', 'controversiality'],
      dtype='object')

In [4]:
df.over_18.value_counts()

over_18
False    623
True       3
Name: count, dtype: int64

In [5]:
df.describe()

,subreddit_subscribers,created_utc,score,num_comments,gilded,num_crossposts,upvote_ratio,link_id,author_fullname,num_reports,depth,controversiality
count,0.0,1.840180e+05,184018.000000,626.000000,184018.000000,626.000000,626.000000,0.0,0.0,0.0,183392.000000,183392.000000
mean,NaN,1.633681e+09,105.371268,856.041534,0.005527,4.274760,0.808866,NaN,NaN,NaN,1.324044,0.028049
std,NaN,1.183404e+08,2906.462531,2151.021512,0.387472,16.627339,0.202740,NaN,NaN,NaN,1.934745,0.165114
min,NaN,1.291310e+09,-728.000000,0.000000,0.000000,0.000000,0.080000,NaN,NaN,NaN,0.000000,0.000000
25%,NaN,1.572981e+09,1.000000,12.000000,0.000000,0.000000,0.650000,NaN,NaN,NaN,0.000000,0.000000
50%,NaN,1.655598e+09,2.000000,78.000000,0.000000,0.000000,0.910000,NaN,NaN,NaN,0.000000,0.000000
75%,NaN,1.737478e+09,7.000000,449.750000,0.000000,2.000000,0.970000,NaN,NaN,NaN,2.000000,0.000000
max,NaN,1.740143e+09,415067.000000,19978.000000,94.000000,269.000000,1.000000,NaN,NaN,NaN,9.000000,1.000000

In [16]:
df.score.max()

np.int64(415067)

In [18]:
score_max = df.score.max()

In [20]:
df['score_norm'] = df.score.apply(lambda s: s/score_max)

In [27]:
df.isna().sum()

element_type                   0
subreddit_id                   0
subreddit_display_name    183392
subreddit_subscribers     184018
post_id                   183392
title                     183392
author                    183415
created_utc                    0
selftext                  183736
score                          0
num_comments              183392
url                       183392
gilded                         0
num_crossposts            183392
over_18                   183392
permalink                 183392
upvote_ratio              183392
comment_id                   626
parent_id                    626
link_id                   184018
author_fullname           184018
author_premium             23132
num_reports               184018
body                         631
edited                       626
depth                        626
controversiality             626
score_norm                     0
dtype: int64

In [34]:
df.post_id.value_counts()

post_id
16amwkm    2
1iu6h79    2
1iuoh8f    2
1iu7gm4    2
1iumcp7    2
          ..
11819v     1
2sybyg     1
1insep6    1
10m1rlf    1
n1s9ub     1
Name: count, Length: 621, dtype: int64

In [46]:
df.post_id.duplicated().sum()

np.int64(183396)

In [55]:
df.loc[(df['element_type'] == 'post') & (df['post_id'].duplicated())]

,element_type,subreddit_id,subreddit_display_name,subreddit_subscribers,post_id,title,author,created_utc,selftext,score,...,parent_id,link_id,author_fullname,author_premium,num_reports,body,edited,depth,controversiality,score_norm
165821,post,2qh0p,robotics,NaN,16amwkm,Join r/AskRobotics - our community's Q/A subre...,t2_1026su,1.693917e+09,Hey Roboticists! \n\n\nOur community has recen...,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000067
165878,post,2qh0p,robotics,NaN,1iu6h79,Who wants to see a Robot Boxing match?,t2_f1g2asnc,1.740078e+09,I got approval from both companies to do this ...,200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000482
165913,post,2qh0p,robotics,NaN,1iuoh8f,3D Printed Pneumatic Artificial Muscles (PAM),t2_ncbigoxv,1.740136e+09,NaN,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000019
165916,post,2qh0p,robotics,NaN,1iu7gm4,eyes/head motion sync test,t2_7dwxk,1.740081e+09,Some custom work done on my KHR-3HV!,132,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000318
165929,post,2qh0p,robotics,NaN,1iumcp7,Blade mantis,t2_8627kfk1,1.740127e+09,NaN,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000022

In [62]:
df.loc[(df['element_type'] == 'comment') & (df['comment_id'].duplicated())]

,element_type,subreddit_id,subreddit_display_name,subreddit_subscribers,post_id,title,author,created_utc,selftext,score,...,parent_id,link_id,author_fullname,author_premium,num_reports,body,edited,depth,controversiality,score_norm
165822,comment,t5_2qh0p,NaN,NaN,NaN,NaN,NaN,1.720588e+09,NaN,4,...,t3_16amwkm,NaN,NaN,False,NaN,First post. Hey robot dudes. I am interested t...,False,0.0,0.0,0.000010
165823,comment,t5_2qh0p,NaN,NaN,NaN,NaN,NaN,1.708717e+09,NaN,3,...,t3_16amwkm,NaN,NaN,False,NaN,"I am not sure that one exists, but I am desper...",False,0.0,0.0,0.000007
165824,comment,t5_2qh0p,NaN,NaN,NaN,NaN,NaN,1.697374e+09,NaN,2,...,t3_16amwkm,NaN,NaN,False,NaN,Hi how to make a path remembering mobile robot?,False,0.0,0.0,0.000005
165825,comment,t5_2qh0p,NaN,NaN,NaN,NaN,NaN,1.700378e+09,NaN,2,...,t3_16amwkm,NaN,NaN,False,NaN,Anyone seeking interns for their projects in H...,False,0.0,0.0,0.000005
165826,comment,t5_2qh0p,NaN,NaN,NaN,NaN,NaN,1.715245e+09,NaN,2,...,t3_16amwkm,NaN,NaN,False,NaN,"Hey, I am just starting my journey in robotics...",False,0.0,0.0,0.000005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165924,comment,t5_2qh0p,NaN,NaN,NaN,NaN,NaN,1.740089e+09,NaN,5,...,t1_mdvb1a5,NaN,NaN,False,NaN,It’s a tinycircuits video kit! No camera curr...,False,1.0,0.0,0.000012
165925,comment,t5_2qh0p,NaN,NaN,NaN,NaN,NaN,1.740087e+09,NaN,2,...,t1_mdvb1a5,NaN,NaN,False,NaN,"Looks like a normal 0.96"" oled screen, I don't...",False,1.0,0.0,0.000005
165926,comment,t5_2qh0p,NaN,NaN,NaN,NaN,NaN,1.740112e+09,NaN,1,...,t1_mdx1e20,NaN,NaN,False,NaN,You can buy a Kondo KHR-3HV! You’ll just have...,False,1.0,0.0,0.000002
165927,comment,t5_2qh0p,NaN,NaN,NaN,NaN,NaN,1.740127e+09,NaN,2,...,t1_mdyf3l0,NaN,NaN,False,NaN,The servos on the robot are kondo KRS2552 R3HV...,False,1.0,0.0,0.000005
165928,comment,t5_2qh0p,NaN,NaN,NaN,NaN,NaN,1.740130e+09,NaN,1,...,t1_mdyhc30,NaN,NaN,False,NaN,"Looks nice, thanks!\n\nhttps://github.com/Armi...",False,2.0,0.0,0.000002

In [74]:
df.loc[(df['comment_id'].duplicated()) & (df['element_type'] == 'post')]

,element_type,subreddit_id,subreddit_display_name,subreddit_subscribers,post_id,title,author,created_utc,selftext,score,...,parent_id,link_id,author_fullname,author_premium,num_reports,body,edited,depth,controversiality,score_norm
1429,post,m0bnr,nextfuckinglevel,NaN,t0hm79,Large crowd of antiwar protestors in St. Peter...,t2_107xeq,1.645727e+09,NaN,277010,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.667386
2549,post,m0bnr,nextfuckinglevel,NaN,j6ed00,This pencil drawing took me over 250 hours to ...,t2_gs8km,1.602021e+09,NaN,276587,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.666367
3565,post,363r3,BeAmazed,NaN,1iup8zf,"After years of being a psychotherapist work, I...",t2_9btzdfpr,1.740139e+09,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
3572,post,363r3,BeAmazed,NaN,1iup9b7,A very creative Vtuber model,t2_7urq9rsa,1.740139e+09,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000007
3576,post,363r3,BeAmazed,NaN,1iuoqfd,Chimpanzees are 5 times stronger than the aver...,t2_u7saom7nv,1.740137e+09,NaN,70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182630,post,2qnts,nottheonion,NaN,11819v,President Obama Has Already Clinched the Elect...,t2_60lcq,1.349827e+09,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
182647,post,2qnts,nottheonion,NaN,2sybyg,Seth Rogen Slams ‘American Sniper': ‘Reminds M...,t2_gjif5,1.421689e+09,NaN,2516,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.006062
183744,post,2qnts,nottheonion,NaN,1insep6,Japan’s Henn na Hotel fires half its robot wor...,t2_o12lw,1.739371e+09,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000002
183762,post,2qnts,nottheonion,NaN,10m1rlf,High egg prices mean an opportunity for substi...,t2_te0sv17b,1.674765e+09,NaN,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000014
183814,post,2qnts,nottheonion,NaN,8dv0h0,"There are 6,000 dogs 'working' at Amazon and t...",t2_4887t,1.524307e+09,NaN,973,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.002344

In [90]:
df.loc[df['parent_id'] == 't3_n1s9ub']

,element_type,subreddit_id,subreddit_display_name,subreddit_subscribers,post_id,title,author,created_utc,selftext,score,...,parent_id,link_id,author_fullname,author_premium,num_reports,body,edited,depth,controversiality,score_norm
1,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619787e+09,NaN,5842,...,t3_n1s9ub,NaN,NaN,False,NaN,Bullet proof glass did its job.,False,0.0,0.0,0.014075
2,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619785e+09,NaN,11693,...,t3_n1s9ub,NaN,NaN,NaN,NaN,I'm thinking a panic button location transmitt...,1619787093.0,0.0,0.0,0.028171
3,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619784e+09,NaN,13631,...,t3_n1s9ub,NaN,NaN,NaN,NaN,"That was actually sick, I wanted to see how it...",False,0.0,0.0,0.032840
4,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619784e+09,NaN,4604,...,t3_n1s9ub,NaN,NaN,False,NaN,He was ready to stand his ground when they got...,False,0.0,0.0,0.011092
5,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619787e+09,NaN,9316,...,t3_n1s9ub,NaN,NaN,False,NaN,My mom used to be the one that would count and...,False,0.0,0.0,0.022445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619791e+09,NaN,1,...,t3_n1s9ub,NaN,NaN,False,NaN,Can someone experienced in this tell me what t...,False,0.0,0.0,0.000002
751,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619791e+09,NaN,1,...,t3_n1s9ub,NaN,NaN,False,NaN,Anyone link to where I can read more about this?,False,0.0,0.0,0.000002
752,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619791e+09,NaN,1,...,t3_n1s9ub,NaN,NaN,False,NaN,The driver was how I like to think I‘d react.....,False,0.0,0.0,0.000002
753,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619791e+09,NaN,1,...,t3_n1s9ub,NaN,NaN,False,NaN,Some John Wick action there!,False,0.0,0.0,0.000002
754,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619791e+09,NaN,1,...,t3_n1s9ub,NaN,NaN,False,NaN,Took em awhile to call back up lol figured he ...,False,0.0,0.0,0.000002

In [86]:
df.loc[df['post_id'] == 'n1s9ub']

,element_type,subreddit_id,subreddit_display_name,subreddit_subscribers,post_id,title,author,created_utc,selftext,score,...,parent_id,link_id,author_fullname,author_premium,num_reports,body,edited,depth,controversiality,score_norm
0,post,m0bnr,nextfuckinglevel,NaN,n1s9ub,Dodging a cash-in-transit robbery. The man has...,t2_8e4s6j2,1.619784e+09,NaN,296541,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.714441

In [ ]:
df.loc[df['element_type'] == 'post'].score_norm.describe()

count    626.000000
mean       0.041648
std        0.110884
min        0.000000
25%        0.000014
50%        0.000578
75%        0.017009
max        1.000000
Name: score_norm, dtype: float64

In [102]:
df.loc[df['element_type'] == 'comment'].score_norm.describe()

count    183392.000000
mean          0.000113
std           0.001196
min          -0.001754
25%           0.000002
50%           0.000005
75%           0.000017
max           0.122012
Name: score_norm, dtype: float64

#### How many comments for each post ?

In [103]:
posts = df.loc[df['element_type'] == 'post']

In [107]:
posts.post_id.duplicated().sum(), posts.post_id.isna().sum()

(np.int64(5), np.int64(0))

In [108]:
# remove duplicates
posts.drop_duplicates(keep='last').reset_index(drop=True, inplace=True)

In [109]:
# now counts comments per post
comments = df.loc[df['element_type'] == 'comment']

In [112]:
comments.comment_id.duplicated().sum(), comments.comment_id.isna().sum()

(np.int64(104), np.int64(0))

In [113]:
comments.drop_duplicates(keep='last').reset_index(drop=True, inplace=True)

In [120]:
comments

,element_type,subreddit_id,subreddit_display_name,subreddit_subscribers,post_id,title,author,created_utc,selftext,score,...,parent_id,link_id,author_fullname,author_premium,num_reports,body,edited,depth,controversiality,score_norm
1,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619787e+09,NaN,5842,...,t3_n1s9ub,NaN,NaN,False,NaN,Bullet proof glass did its job.,False,0.0,0.0,0.014075
2,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619785e+09,NaN,11693,...,t3_n1s9ub,NaN,NaN,NaN,NaN,I'm thinking a panic button location transmitt...,1619787093.0,0.0,0.0,0.028171
3,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619784e+09,NaN,13631,...,t3_n1s9ub,NaN,NaN,NaN,NaN,"That was actually sick, I wanted to see how it...",False,0.0,0.0,0.032840
4,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619784e+09,NaN,4604,...,t3_n1s9ub,NaN,NaN,False,NaN,He was ready to stand his ground when they got...,False,0.0,0.0,0.011092
5,comment,t5_m0bnr,NaN,NaN,NaN,NaN,NaN,1.619787e+09,NaN,9316,...,t3_n1s9ub,NaN,NaN,False,NaN,My mom used to be the one that would count and...,False,0.0,0.0,0.022445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184013,comment,t5_2qnts,NaN,NaN,NaN,NaN,NaN,1.524415e+09,NaN,7,...,t1_dxqt3kj,NaN,NaN,False,NaN,"No, no, he's not a Nazi! He's a ""Race realist""...",False,8.0,0.0,0.000017
184014,comment,t5_2qnts,NaN,NaN,NaN,NaN,NaN,1.524346e+09,NaN,2,...,t1_dxqz6b6,NaN,NaN,False,NaN,Looks like someone is too full of ideology to ...,False,8.0,1.0,0.000005
184015,comment,t5_2qnts,NaN,NaN,NaN,NaN,NaN,1.524346e+09,NaN,8,...,t1_dxqyw66,NaN,NaN,False,NaN,You really are a not very nice human being,False,9.0,0.0,0.000019
184016,comment,t5_2qnts,NaN,NaN,NaN,NaN,NaN,1.524352e+09,NaN,0,...,t1_dxr1jd2,NaN,NaN,False,NaN,"So they piss in bottles to meet deadlines, big...",False,9.0,0.0,0.000000
184017,comment,t5_2qnts,NaN,NaN,NaN,NaN,NaN,1.524413e+09,NaN,2,...,t1_dxr4wk5,NaN,NaN,NaN,NaN,They need urinal bots that you can call over w...,False,1.0,0.0,0.000005

In [125]:
comments['parent_id_parsed'] = comments['parent_id'].apply(lambda p_id: p_id.split('_')[-1])

C:\Users\tommy\AppData\Local\Temp\ipykernel_22548\638405820.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comments['parent_id_parsed'] = comments['parent_id'].apply(lambda p_id: p_id.split('_')[-1])

In [128]:
posts['post_id']

0          n1s9ub
1429       t0hm79
2549       j6ed00
3565      1iup8zf
3572      1iup9b7
           ...
182630     11819v
182647     2sybyg
183744    1insep6
183762    10m1rlf
183814     8dv0h0
Name: post_id, Length: 626, dtype: object